// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactWindow = require("react-window");

function make(height, itemCount, itemSize, width, children) {
  return ReasonReact.wrapJsForReason(ReactWindow.FixedSizeList, {
              height: height,
              itemCount: itemCount,
              itemSize: itemSize,
              width: width
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
